.github/workflows/run-checks.yaml

This reverts commit 071a704fb1cc83ccdb3a3ac4f506c2789b79b35a.

Revert "fix: temporary close lighthouse ci"

---

.github/pull_request_template.md

The old template was cluttered, had grammatical errors, and required a lot of filling
- fixed grammatical errors
- pre-filled demo link as dev environment
- remove unused sections
#262 (this pr itself)

Refine pull request template

---

README.md

- The readme page proposed by @saenyakorn is in Thai, while almost everything else is in English
- Translated the readme to English and adjusted it as I see fit
[https://github.com/thinc-org/cugetreg-frontend/blob/pun/docs/readme/README.md](https://github.com/thinc-org/cugetreg-frontend/blob/pun/docs/readme/README.md)

Translate readme to English

---

src/modules/Schedule/components/ScheduleTable/components/ScheduleTableCard/index.tsx
src/modules/Schedule/components/ScheduleTable/components/ScheduleTableCard/styled.tsx

After loading the page, the schedule items will bounce horizontally.
https://user-images.githubusercontent.com/8080853/145019705-be7f4938-8b06-4aa8-9c72-27c2d962c992.mov
- Changed initial drag position to 0 to fix the bounce effect
[https://dev.cugetreg.com/S/schedule](https://dev.cugetreg.com/S/schedule)

Fix schedule items bouncing on load

---

src/pages/about/index.tsx

- About page is outdated. It was made before course descriptions and reviews existed.
- Updated the source of our data including course description
- Add review to benefits of logging in

Update about page

---

src/pages/privacy/index.tsx

- The privacy policy is outdated
- Remove Google Drive App Data from information we collect and add Email instead.
- Add more core functionality that uses the information
[https://dev.cugetreg.com/privacy](https://dev.cugetreg.com/privacy)

fix: update privacy policy

---

src/pages/about/index.tsx

- Sports center booking is open now
- Add link to CUSC Booking

fix: update about page

---

src/modules/Schedule/components/CourseDialog/components/CourseDialogDetail.tsx

- Forgor
- Fix chip for specific section in CourseDialog
https://user-images.githubusercontent.com/51981658/145971937-21200d4c-89b6-4637-bfed-820004d81ec5.mov

Fix chip in CourseDialog

---

src/common/utils/loginGuard/index.tsx
src/modules/CourseDetail/components/ReviewForm/index.tsx

- ลืมใส่ userStore.login() 
- 

fix user login after activate loginGuard

---

src/modules/CourseDetail/components/ReviewForm/index.tsx
src/modules/CourseDetail/context/Review/index.tsx

fix change default semester

---

src/lib/dialog/components/Dialog.tsx
src/modules/CourseDetail/components/ReviewCard/__snapshots__/index.test.tsx.snap
src/modules/CourseDetail/components/ReviewCard/index.test.tsx
src/modules/CourseDetail/components/ReviewCard/index.tsx
src/modules/CourseDetail/context/Review/index.tsx
src/modules/CourseSearch/__snapshots__/index.test.tsx.snap
src/modules/CourseSearch/components/CourseList/components/Courses/index.tsx
src/modules/CourseSearch/index.test.tsx
src/modules/CourseSearch/index.tsx

Fix tiny thing

---

src/modules/CourseDetail/components/ControlledSelect/index.tsx
src/modules/CourseDetail/components/ReviewCard/index.tsx
src/modules/CourseDetail/components/ReviewForm/functions.ts
src/modules/CourseDetail/components/ReviewForm/index.tsx
src/modules/CourseDetail/components/ReviewForm/types.ts
src/modules/CourseDetail/context/Review/index.tsx
src/modules/CourseDetail/index.tsx

- when editing a review, the academicYear and semester dropdown values aren't restored
- when scrolling to review form, there is too much top offset and part of the form is obstructed in small screens
- the spacing is a little bit weird
- fixed those three issues
[https://dev.cugetreg.com/S/courses/0201122](https://dev.cugetreg.com/S/courses/0201122)

Improve review form

---

src/common/components/TopBar/components/GDriveIndicator/index.tsx
src/common/i18n/locales/th.ts

- The sync status error message is outdated and still refers to Google Drive
- Updated the error message

Update sync status message

---

src/common/components/TopBar/components/MobileNavBar/styled.ts
src/common/components/TopBar/components/UserButton/styled.ts

Fix drawer stretching when username is too long

---

src/modules/CR11/index.tsx
src/modules/Schedule/index.tsx
src/pages/about/index.tsx

- We only added page titles for course search and course detail page
- Added title for other pages

Add title to other pages

---

src/modules/Schedule/hooks/useRemoveCourse.tsx
src/store/courseCart.ts

- Sync fails when undoing course removal
- Fixed the error

Fix sync fail when undoing remove course

---

src/common/utils/getExamDate/index.ts

fix: midterm exam date display final exam date

---

src/modules/CourseSearch/components/RecommendationText/index.tsx
src/modules/CourseSearch/components/RecommendationText/types.ts

Deploy to production (9 Jan 2022)

---

src/modules/CourseSearch/__snapshots__/index.test.tsx.snap
src/modules/CourseSearch/components/RecommendationText/index.tsx
src/modules/CourseSearch/index.tsx

- Recommendation text has been sitting for too long after experiment success.
- Integrate recommendation text

Integrate recommendation text

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
docs/CHANGELOG.md

Sync beta with master

---

src/common/components/TopBar/components/TermDropdown/index.tsx
src/common/constants/terms.ts
src/common/utils/getCurrentTerm/index.ts
src/modules/CourseSearch/index.tsx

Update current term

---

src/common/tracker/index.ts
src/env/index.ts
src/services/logging/index.ts

Disable logging

---

src/common/constants/terms.ts

- It's almost time for semester 1/2565
- Add semester 1/2565 to term list

feat: add 2565/1

---

src/common/components/CookieBanner/components/CookieSettings/index.tsx

[Fix] default consent without pushing to dataLayer

---

.env.prod

[Fix] API endpoint for prod

---

.env
.env.dev
next.config.js
src/modules/Schedule/components/Schedule/utils/getOverlappingCourses/index.test.ts
src/modules/Schedule/components/Schedule/utils/getOverlappingCourses/index.ts

Fix schedule page crash

---

package.json
src/common/components/TopBar/components/NavBar/index.tsx
src/modules/App/__snapshots__/index.test.tsx.snap
src/modules/CourseSearch/__snapshots__/index.test.tsx.snap
src/modules/CourseThumbnailAPI/drawThumbnail.ts
yarn.lock

- Got email from dependabot security alert
- `yarn upgrade`
✅  [https://dev.cugetreg.com](https://dev.cugetreg.com)

bump dependencies

---

src/modules/Schedule/components/Schedule/components/ClassCard.tsx

Swap building and section

---

src/modules/Schedule/components/Schedule/components/ClassCard.tsx

- https://cugetreg.slack.com/archives/C02U3BQ0XA9/p1659926831311149
- 

Show classroom in schedule page

---

src/common/components/Footer/components/Banner/index.tsx

- The button says "Setting Cookies"
- Changed it to "Privacy Preference"

Fix cookie dialog wording

---

src/common/components/Footer/components/Banner/index.tsx

Deploy to production

---

src/common/components/CookieBanner/components/CookieSettings/index.tsx

- cannot close the dialog by clicking the backdrop
- change the behavior

[Fix] Cookie Setting Dialog behavior

---

.github/workflows/deploy.yaml

[Fix] use SSH_PASSPHRASE

---

apps/cugetreg-api/src/common/scalars/date.scalar.ts
apps/cugetreg-api/src/course/course.enum.graphql
apps/cugetreg-api/src/course/course.graphql
apps/cugetreg-api/src/graphql.ts
apps/cugetreg-api/src/override/override.graphql
apps/cugetreg-api/src/review/review.graphql
apps/cugetreg-api/src/review/review.service.ts
apps/cugetreg-api/src/user/user.graphql

- There's no GraphQL doc at the moment.
- Added GraphQL documentation for Course, Override, Review, and User API
- Removed some unused GraphQL types
- Add some data validation to review service to match the docs

add GraphQL documentation (except computation)

---

.github/workflows/deploy.yaml

[Fix] Publish Docker image using Nx configuration

---

apps/cugetreg-web/next-sitemap.config.js
apps/cugetreg-web/project.json

[Fix] Sitemap config

---

.github/workflows/deploy.yaml

[Fix] Action pull wrong image 

---

apps/cugetreg-api/Dockerfile

[Fix] Backend Export Port

---

.github/workflows/deploy.yaml

There's a small bug in #382 that breaks the deploy step when there are more than 1 affected app.
Fixed the broken environment variable assignment.

[Fix] Add quotes to AFFECTED_APPS in deploy step

---

apps/cugetreg-api/src/main.ts
apps/cugetreg-web/src/pages/_app.tsx

- เนื่องจากเมื่อกี้ #389 มันมี change แค่ workflow เลยไม่ publish & deploy docker image 
- เพิ่ม change ใน frontend และ backend
- **ทำแค่ครั้งนี้ครั้งเดียว ที่เหลือ automate detect change เองได้หมด**

[Hotfix] Add temporary commit

---

.github/workflows/deploy.yaml
apps/cugetreg-api/Dockerfile
apps/cugetreg-web/Dockerfile
tools/set-affected-apps-env

This fixes #395 
Switched frontend node image from `alpine` to `buster`, and pinned node version to be the same everywhere.
[https://dev.cugetreg.com/S/courses/0201106](https://dev.cugetreg.com/S/courses/0201106)

Fix server error on course detail page

---

.eslintrc.json
apps/cugetreg-web/src/common/components/CookieBanner/components/CookieSettings/index.tsx
apps/cugetreg-web/src/common/components/RichTextEditor/components/ToolbarButton/index.tsx
apps/cugetreg-web/src/components/RenderOnIntersect.tsx
apps/cugetreg-web/src/modules/CourseSearch/hooks/useSearchCourseQueryParams/utils/removeUndefinedValue/index.ts
apps/cugetreg-web/src/pages/server-site.xml/index.tsx
package.json

Code Quality
- Fix ESLint Warnings
- Disable no-explicit-any in Unit Test
(Those actions not required)

fix(nx): eslint warnings

---

.github/workflows/reusable-ci.yaml

- CI always fail when open Pr
Closes #442 
- Fix base ref when running nx affected

[Fix] CI Failed due to missing base ref 

---

.github/workflows/reusable-ci.yaml

- I set wrong default base ref
- I changed it to `master` instead of `main`

[Fix] CI fail when squashing commit 

---

tools/gened/README.md
tools/gened/requirement.txt
tools/gened/upload_override_gened_sections.py

- Add local env for gened tool
- Add local env for gened tool

Add local environment

---

.github/workflows/deploy.yaml

Fixes #450 
- Change image pull command to pull correct image in workflow

fix: ci cd wrong image tag

---

apps/api/src/graphql.ts
apps/api/src/review/review.graphql
apps/api/src/review/review.resolver.ts
apps/api/src/review/review.service.ts
apps/api/src/schemas/review.schema.ts
apps/web/src/__mock__/review.ts
apps/web/src/common/types/reviews.ts
apps/web/src/modules/CourseDetail/components/ReviewCard/__snapshots__/index.test.tsx.snap
apps/web/src/modules/CourseDetail/components/ReviewCard/index.test.tsx
apps/web/src/modules/CourseDetail/components/ReviewCard/index.tsx
libs/codegen/src/generated/index.tsx
libs/codegen/src/query/fragments.graphql

- Add course review rejection reason (Closes #420)
- Update Mongoose schema, GraphQL schema, and edit `web` to display rejection reason

Add course review rejection reason

---

.github/workflows/deploy.yaml
apps/api/src/auth/auth.service.ts

- CGR Crashed due to parallel save
- Add forgotten await for save

fix: possible crash due to un-awaited save

---

.changeset/early-dryers-sip.md
.changeset/pre.json
apps/web/CHANGELOG.md
apps/web/Dockerfile
apps/web/package.json

Deploy production 05/02/2023

---

.changeset/nice-ladybugs-give.md
.changeset/pre.json
.github/workflows/sync-beta.yaml
apps/admin-api/package.json
apps/api/package.json
apps/reg-scraper/package.json
pnpm-lock.yaml

Deploy hotfix dependency problem

---

apps/web/package.json

- I can't run dev in windows.
- Change "PORT=" to "-p " 

fix: can't run dev on windows

---

apps/web/package.json

- #498 , but forgot to squash merge

fix: port web dev

---

.changeset/bright-pets-wait.md
.changeset/config.json
package.json
packages/codegen/codegen.yml
packages/codegen/package.json
pnpm-lock.yaml

Codegen now work in this new turborepo

refactor(codegen): codegen for turborepo

---

.github/workflows/update-gitops.yaml

Skip update gitops when folder does not exist

---

.github/workflows/reusable-ci.yaml

[Fix] Use filter for running CI when base branch is not main

---

.changeset/smooth-terms-shout.md
apps/admin-web/src/common/HighlightHTML/index.tsx

- Because `admin-web` build is failing right now
- Remove undeclared config variables

fix undeclared mui config variable

---

.changeset/pre.json
.changeset/weak-oranges-exist.md
apps/web/CHANGELOG.md
apps/web/Dockerfile
apps/web/package.json

Deploy production 01/03/2023

---

.changeset/ten-cars-clap.md
.github/workflows/e2e.yaml
.github/workflows/pre-release.yaml
.github/workflows/release-without-versioning.yaml
.github/workflows/release.yaml
.github/workflows/reusable-ci.yaml
.github/workflows/sync-beta.yaml
.npmrc
.nvmrc
apps/api/Dockerfile
apps/reg-scraper/Dockerfile
apps/web/Dockerfile
apps/web/package.json
package.json
pnpm-lock.yaml

feat: upgrade to node 18

---

.github/workflows/e2e.yaml
.github/workflows/release-without-versioning.yaml
.github/workflows/release.yaml
.github/workflows/reusable-ci.yaml
package.json
pnpm-lock.yaml

chore: pnpm 8

---

.changeset/large-crews-cough.md
apps/web/src/common/constants/terms.ts

Add 2565/ฤดูรัอน

---

.changeset/sixty-dolls-admire.md
apps/web/src/common/constants/terms.ts

add 2566/1

---

.changeset/modern-buses-change.md
.changeset/pre.json
apps/web/CHANGELOG.md
apps/web/package.json
apps/web/src/common/constants/terms.ts
apps/web/src/common/utils/getCurrentTerm/index.ts

Deploy production 28/06/2023

---

.changeset/big-tomatoes-sleep.md
.changeset/dry-trainers-knock.md
.changeset/pre.json
apps/web/CHANGELOG.md
apps/web/package.json
apps/web/src/common/utils/getExamPeriod/index.ts
apps/web/src/modules/CourseDetail/index.tsx
apps/web/src/modules/CourseSearch/index.tsx
apps/web/src/modules/Schedule/components/CourseDialog/components/CourseDialogDetail.tsx

Summary
- https://github.com/thinc-org/cugetreg/pull/598
- https://github.com/thinc-org/cugetreg/pull/602

Deploy production 21/07/2023

---

.changeset/dry-crabs-thank.md
.changeset/pre.json
apps/web/CHANGELOG.md
apps/web/package.json
apps/web/src/modules/Schedule/components/CourseDialog/components/CourseDialogDetail.tsx

Summary
- https://github.com/thinc-org/cugetreg/pull/605

Deploy production 23/07/2023

---

.changeset/light-cooks-thank.md
apps/web/src/modules/CourseDetail/index.tsx

Add S/U field in course page
Subject is S/U if 'S/U' in credit_hours

feat(web): add S/U field in course page

---

.changeset/light-cooks-thank.md
.changeset/pre.json
apps/web/CHANGELOG.md
apps/web/package.json
apps/web/src/modules/CourseDetail/index.tsx

Deploy production 9/8/2023

---

.changeset/violet-sloths-reply.md
apps/admin-api/package.json
apps/api/package.json
apps/reg-scraper/package.json
packages/schema/package.json
pnpm-lock.yaml

chore: bump mongoose (fix vulnerabilities)

---

.changeset/thin-houses-rhyme.md
apps/web/src/common/components/TopBar/components/AnnouncementBar/announcements.ts
apps/web/src/common/components/TopBar/components/AnnouncementBar/index.tsx
apps/web/src/common/components/TopBar/components/AnnouncementBar/types.ts
apps/web/src/common/components/TopBar/index.tsx

feat(web): not reg chula warning

---

.changeset/lucky-phones-listen.md
apps/web/src/modules/CourseSearch/components/RecommendationText/index.tsx

best way to deal with useEffect is to not use useEffect

fix(web): recommendation crashing website

---

.changeset/wise-bottles-mate.md
apps/web/package.json
apps/web/src/common/i18n/locales/th.ts
apps/web/src/modules/Schedule/ics.ts
apps/web/src/modules/Schedule/index.tsx
pnpm-lock.yaml

feat(web): exam ics

---

.changeset/cold-fishes-greet.md
.changeset/pre.json
apps/admin-api/CHANGELOG.md
apps/admin-api/package.json
apps/api/CHANGELOG.md
apps/api/package.json
apps/reg-scraper/CHANGELOG.md
apps/reg-scraper/package.json
apps/web/CHANGELOG.md
apps/web/package.json
apps/web/src/common/components/TopBar/index.tsx
pnpm-lock.yaml

Deploy Production 9/6/2567

---

packages/ui/src/components/atom/recommended-tag/recommended-tag.svelte

fix recommended-tag : darkmode,z-value
-

fix recommended-tag : darkmode,z-value

---

.changeset/pre.json
.changeset/silly-rivers-hear.md
apps/web/CHANGELOG.md
apps/web/package.json
apps/web/src/common/components/TopBar/components/AnnouncementBar/announcements.ts
apps/web/src/common/components/TopBar/index.tsx
apps/web/src/common/constants/terms.ts

Change Default Semester to 2567/2

Deploy Production 15/1/2568
