thinc-org/cugetreg

- src/common/utils/getCourseKeyString/index.ts
- src/common/utils/types.ts
- src/modules/CourseSearch/components/CourseList/components/Courses/index.tsx
- src/store/courseCart.ts
This fixes #232
- (Optional) Link for [Figma]()
- (Optional) Other [Resources]()
Previously, the course search page used `course.courseNo` as the key for course card items, causing invalid states in cards to stay. This crashes the app when switching between semesters because the selected section doesn't exist.
Changed the key to be a combination of `courseNo`, `studyProgram`, `academicYear`, and `semester`.
-
> Fix course card key

- src/modules/Schedule/components/Schedule/utils/index.ts
- (Optional) Link for [Figma]()
- (Optional) Other [Resources]()
Some courses have duplicated class data, which cause schedule to highlight the course in red.
Ignore overlap from classes in the same course.
-
> Don't warn about a course overlapping itself

- dockerfile
- (Optional) Link for [Figma]()
- (Optional) Other [Resources]()
#251 broke the course detail page
Switch to the old method (running `npm prune`), but move pruning into a new build stage. This allows us to utilize build cache, and simultaneously run build and prune.
-
> Prune dependencies in a separate build stage

- package.json
- yarn.lock
- Since [`@mui/styles`](https://mui.com/styles/basics/#main-content) is deprecated in MUIv5 and it contains legacy jss solution 
- I forgor 💀 
- Remove `@mui/styles` 
> fix: remove jss dependency

- src/services/apollo/index.ts
- src/store/courseCart.ts
- When restoring course cart from backend, each corses are fetched sequentially
- Initiate fetching of all courses simultaneously
- Turned on batching in Apollo client
> Batch schedule course data fetching

- src/configs/theme/typography.ts
- This PR fixes ChulaCharas font vowels and tone marks positioning.
- Force enable ligature (`liga`) which is a workaround that majority of Thai fonts use to positioning vowels and tone marks. (It is enabled by default but setting `letterSpacing` disabled it)
- Note that another font (Prompt) doesn't have this problem since it uses a newer (and straightforward) OpenType feature.
https://user-images.githubusercontent.com/30551284/154838856-875079d1-11e0-478b-b723-f24c5596abf6.mp4
> fix: ChulaCharas font vowels and tone marks positioning

- package.json
- yarn.lock
- This PR fixes the RichTextEditor delete backward behavior for Thai script where deleting N character(s) backward should delete N code point(s) instead of an entire grapheme cluster.
- The `Transform.delete` method of Slate (the package that Plate built on top of) was modified so that it insert back code point of Thai script that should remain upon delete backward.
- As far as I concerned, there is no breaking change to upgrade from 0.72.0 to 0.81.1, per the [CHANGELOG](https://github.com/ianstormtaylor/slate/blob/main/packages/slate/CHANGELOG.md)
Before:
https://user-images.githubusercontent.com/30551284/173242116-d0af41d4-a2b8-4676-9d98-93455d70d65a.mp4
After:
https://user-images.githubusercontent.com/30551284/173242124-c7f9b507-24d4-49ee-bbde-2af0d4dcf350.mp4
- …
> Fix RichTextEditor delete backward behavior for Thai script

- apps/cugetreg-web/src/common/components/CookieBanner/components/CookieSettings/index.tsx
- apps/cugetreg-web/src/common/components/CookieBanner/index.tsx
- apps/cugetreg-web/src/common/components/Footer/components/Banner/index.tsx
- apps/cugetreg-web/src/store/consents.ts
See #377
Changed the consent banner and dialog behavior as follow:
- Opening the settings dialog no longer closes the banner
- Clicking confirm in the dialog will save the changes and close the banner
> [Fix] Cookie banner reappearing

- .github/workflows/deploy.yaml
- เนื่องจาก workflow_dispatch ไม่มี `github.event.before` ทำให้ check affacted กับ commit ก่อนหน้าไม่ได้
- ซึ่งเราอาาจะแก้ได้โดยใช้ git CLI ในการหา commit sha ก่อนหน้า แต่ก็จะมีกรณี ถ้าเรา merge จาก beta / hotfix เข้า master เยอะ แล้ว dispatch ทีเดียวแล้วจะเทียบกับ commit ไหน (จะหายังไง)
- ซึ่งจากข้อ 2 เราอาจจะใช้ git tag ในการ detect commit ที่มี tag ล่าสุดได้ ด้วย `git show-ref --tags | tail -1 | awk '{print $1}' ` แต่ก็จะซับซ้อนมากขึ้น ซึ่งเรื่อง tag เดี๋ยวมาทำอีกที 
- จากทั้งหมดที่กล่าวมา เลยคิดว่า เปลี่ยน workflow_dispatch เป็น push event สำหรับ master branch น่าจะง่ายที่สุดในเวลานี้แล้ว
> [Hotfix] Change trigger event for master branch

- apps/cugetreg-web/src/configs/theme/articletext.ts
- apps/cugetreg-web/src/pages/about/index.tsx
- This PR fixes hydration failed in about page causing by having invalid ul element in p tag.
This PR is believed to solve the problem where visiting [https://cugetreg.com/about](https://cugetreg.com/about) on first load or refreshing 1 time after route change will cause `[Facebook Page: Thinc.]` in `ติดต่อทีมงาน` section to be linked to problem report form.
- Changes `StyledArticleBody` which resolves to `p` tag to `StyledArticleBox` which resolves to `div`.
- https://stackoverflow.com/questions/71706064/react-18-hydration-failed-because-the-initial-ui-does-not-match-what-was-render
> Fix about page hydration failed

- apps/cugetreg-api/src/course/course.service.ts
- apps/cugetreg-api/src/util/functions.ts
Currently, when searching courses, the keyword is dangerously fed into the RegExp pattern and sent to MongoDB. With certain patterns (`([A-Z ]+)+l` for example), it can cause the server to take insane amount of time and processing power to process the request, which can cause the server to be unresponsive.
Thanks @saengowp for the report.
- Escape the keyword before passing them to MongoDB
Here is the result after the fix.
> CRITICAL FIX: escape regex string used in search

- apps/cugetreg-api/src/auth/auth.service.ts
- https://beta.cugetreg.com authentication is broken, because if duplicate /api suffix in default callback url (since /_api is already present in env)
- Removed duplicate `/api` suffix
> fix: remove /_api suffix

- apps/cugetreg-api/.gitignore
- apps/cugetreg-api/src/graphql.ts
- apps/cugetreg-api/src/override/override.graphql
- apps/cugetreg-api/src/override/override.resolver.ts
- apps/cugetreg-api/src/schemas/override.schema.ts
Override schema in `cugetreg-api` does not match the one in [thinc-org/cugetreg-scraper](https://github.com/thinc-org/cugetreg-scraper). I don't know how the fuck it worked until now.
- Update `override.schema.ts` to match the one used by scraper
- Added `semester` and `academicYear` fields
- Use enums in graphql declaration for schema declaration, instead of using [thinc-org/chula-courses](https://github.com/thinc-org/chula-courses)
- Add `overrides` query to return all overrides (this was already implemented in OverrideService, it just wasn't exposed as a query)
- Note: this query is intentionally left unprotected since it's public data
> fix: update override schema to match scraper

- apps/cugetreg-api/src/schemas/course.schema.ts
- apps/cugetreg-api/src/schemas/review.schema.ts
ok im sorry, i know we agreed we won't be coding anymore, but i just can't help it
- We created indices manually on MongoDB production db, but we forgot to ensure it in the source code. This is why it's slow on beta and dev. It's also tiresome when we want to add new indices, since we have to manually ssh and create indices on all 3 environments
- Removed old index (`studyProgram, academicYear, semester`) in favor of the new ones
- Ensure indices on the following collections
All queries to course have `studyProgram, academicYear, semester`, so it'll **always** utilize either of these indices at minimum. This also makes scraper save much faster too (from ~1,900 seconds to ~800 seconds).
1. (`studyProgram, academicYear, semester, courseNo`) -> fast query during search with courseNo, …
> Ensure indices on course and review collections

- apps/cugetreg-api/src/graphql.ts
- apps/cugetreg-api/src/override/override.graphql
- apps/cugetreg-api/src/override/override.resolver.ts
- apps/cugetreg-api/src/override/override.service.ts
- `createOrUpdateOverride` and `deleteOverride` is supposed to identify overrides with `semester` and `academicYear` also, but i forgot to implement it.
- Make both mutations use `semester` and `academicYear` in their queries.
> fix override mutation apis to correctly identify overrides

- .github/workflows/deploy.yaml
- tools/set-affected-apps-env
When force pushing to a branch, we don't have the 'before' commit in the local git tree, making it impossible to compare changes against, so we used building all apps as fallback.
Use the checkout action to checkout the 'before' commit, then continue the process as normal. This way, the 'before' commit will be available for comparison.
Also removed checkout for PRs because we don't do deploy on PRs.
- [Run #231](https://github.com/thinc-org/cugetreg/runs/8198475254?check_suite_focus=true): Force push, all apps changed
- [Run #232](https://github.com/thinc-org/cugetreg/runs/8198519894?check_suite_focus=true): Force push, no apps changed
> Checkout 'before' ref for compare

- apps/cugetreg-web/src/common/components/TopBar/components/ConfigSelect/index.tsx
- I have found that StudyProgramDropdown choice and TermDropdown choice have text color that blend with background color if it does not hover at width 600px - 960px
- I have fixed ConfigSelect to correctly display text color
> Fix inconsistent background color in ConfigSelect

- README.md
- Fix Wrong Document Link in Readme.md Result in wrong result
- Change link from old repository (frontend) to https://github.com/thinc-org/cugetreg/wiki/Contribution-Guide
> Fix Readme.md Contribution Guide Link

- apps/api/src/review/review.service.ts
- Reviews were being sorted by oldest first (_id ascending). It's better if it's most recent first (_id descending)
- Sort reviews by _id descending
> sort reviews by _id descending

- .github/workflows/release-dev.yaml
To follow up unresolved comments in #470.
The following improvements in the release-dev workflow
- Only install turbo cli instead of **all** dependencies
- Use jq map to transform values instead of manual concatenation
[Action run](https://github.com/thinc-org/cugetreg/actions/runs/4076331027/jobs/7023917355)
Before:
After:
> Follow up #470: improve release-dev workflow

- .changeset/early-dryers-sip.md
- .changeset/pre.json
- apps/web/Dockerfile
- Web prod threw this error
Which seems like it was missing dependencies in the runtime, weirdly
- Install `cairo` and `pango` in runtime stage
> add lib to web dockerfile

- .changeset/pre.json
- .github/workflows/sync-beta.yaml
- When we merge changeset's Version Packages PR (see #486), it removes the pre-release configuration and other changeset files. We want those changes to reflect back to beta so those changesets don't appear again when we merge beta to main later.
- Created a workflow file, which executes when the PR is merged and the source branch is `changeset-release` and target branch is `main`. When executed, rebases `beta` branch onto `main`.
https://github.com/bombnp/actions-playground/actions/runs/4095898138/jobs/7063149157
> Sync beta to main after merging Version Packages PR

- .changeset/nice-ladybugs-give.md
- apps/admin-api/package.json
- apps/api/package.json
- apps/reg-scraper/package.json
- pnpm-lock.yaml
- Read #489 
- Fixes #489 
This is a short term solution. We should not be required to add `class-validator` and `class-transformer` to all nest apps.
> add class validator and class transformer in all nest apps

- .github/workflows/deploy-docker.yaml
- .github/workflows/release-dev.yaml
- .github/workflows/release.yaml
- We cannot publish dev Docker images for now
- @saenyakorn changes
- Filter `//` from `affectedPackages`
- @bombnp changes
- Add field `ref` and `imageTag` to specify which ref to checkout and what tag to tag the docker image
- Transform publishedPackages to packagesToBuild to use with docker build workflow
- Remove `latest` tag since we don't use it at all (better to not have it than have it be incorrect)
> Fix dev workflow

- docker-compose.yaml
- If the Docker network `cugetreg-network` hasn't been created on one's machine before, the compose file will fail to start due to
```
service "mongo" refers to undefined network cugetreg-network: invalid compose project
```
- If the `cugetreg-network` exists on one's machine, they should add the `external` key by themselves instead
- Add `cugetreg-network` to networks in `docker-compose.yaml`
(inapplicable)
> Fix docker compose undefined network

- .changeset/funny-ducks-wash.md
- apps/web/src/common/components/GoogleOneTapPrompt/hooks/useGoogleOneTap/index.ts
For browsers that support ITP (Intelligent Tracking Prevention), the Google Sign-In JavaScript library will display a generic prompt instead of the one pre-filled with `student.chula.ac.th` user accounts.
Clicking on `Continue` will open an account selection/sign-in popup in which the `hosted_domain` config hasn't been taken into account. Therefore, users could select generic Google accounts or accounts of other domains and get denied eventually, resulting in bad UX. To fix this problem, ITP support could be disabled.
- Disable Google One Tap Prompt for ITP browsers
[https://dev.cugetreg.com](https://dev.cugetreg.com) - dev is not working right now
> Disable Google One Tap for ITP browsers

- .changeset/spotty-apples-invent.md
- apps/web/src/common/components/GoogleOneTapPrompt/hooks/useGoogleOneTap/index.ts
- apps/web/src/store/userStore.ts
Related to Google One Tap,
- > the prompt still pops up even if I'm logged in. Is there a way to make the prompt not appear if logged in?
- Wait for `userStore` to initialize before prompting Google One Tap
> Wait for userStore to initialize before prompting Google One Tap

- .changeset/pretty-lions-applaud.md
- apps/web/src/common/components/GoogleOneTapPrompt/hooks/useGoogleOneTap/index.ts
- apps/web/src/store/userStore.ts
The Sign In with Google client library offers an automatic sign in feature that helps improve the UX. When entering the app, the user will be automatically signed in if they have granted access in the past. 
This can be useful when the user has multiple devices, or revisiting users that lost their session.
Related documentation: [Automatic sign-in and sign-out](https://developers.google.com/identity/gsi/web/guides/automatic-sign-in-sign-out)
Enabled the auto sign in flow, and disable it when the user explicitly signs out.
Dev is broken, no demo for you 😢
> Enable automatic sign in flow

- .changeset/light-badgers-boil.md
- apps/admin-web/next.config.js
- apps/web/next.config.js
The next config was set to remove all console.log statements, which could make debugging difficult.
Disabled the removal in dev server, and only enable it in the build output.
> Retain console.log in non-production environments

- .github/workflows/deploy-docker.yaml
- .github/workflows/release-dev.yaml
- .github/workflows/release-without-versioning.yaml
- .github/workflows/release.yaml
- .github/workflows/update-gitops.yaml
-
- Add `update-gitops.yaml` workflow for open PR to cugetreg-gitops repo
- Add `gitops-mode` to choose between `PR` or `commit` 
- When we push something to to `dev`, the action will calculate affected packages and push kustomize changed to gitios repo.
- When we push something to `beta`, the action will do pre-release thing, and then open the Pre-release PR. After we merge the PR, the action will bump the package version, build the docker images and open kustomize changed PR to GitOps repo.
- Similar to `beta`, when we push something to `main`, the action will do release thing, and the rest is the same as `beta`'s flow. 
Workflow https://github.com/thinc-org/cugetreg/actions/runs/4106806503
Success Commit - https://github.com/thinc-org/cugetreg-gitops/commit/ac296cee9f9ada87fc91369eda675 …
> [Feat] Add update GitOps repository workflow

- .changeset/long-seals-clean.md
- apps/web/src/common/components/GoogleOneTapPrompt/hooks/useGoogleOneTap/index.ts
As mentioned in #501, the Google One Tap should not be prompted on ITP browsers. However, a typo was made in the config param, making it still prompt.
- Correct: `itp_support`
- Wrong: `itp_supported`
The TypeScript type check does not catch this error due to the entire config object was cast to `IdConfiguration` to add support for the undocumented `hosted_domain` param.
- Correct the typo
- Extend the `IdConfiguration` type to add the `hosted_domain` param to allow type checking, before casting it back to `IdConfiguration`.
Any better solution is welcome.
> Hotfix typo in Google One Tap ITP config

- .changeset/nasty-hats-visit.md
- apps/web/src/common/components/GoogleOneTapPrompt/hooks/useGoogleOneTap/index.ts
#515 contains a change that does not support TypeScript 4.7, so this PR fixes it.
> Remove unsupported feature for TypeScript 4.7

- .github/workflows/deploy-docker.yaml
- Because this error https://github.com/thinc-org/cugetreg/actions/runs/4157069395, if we don't have environment-specific env. It should use `.env` or nothing instead.
- Check if file exists before move `.env`
> [Fix] Add more conditions for setup frontend env 

- .github/workflows/deploy-docker.yaml
- Currently, when frontend checks for frontend env files, it uses "-d", but it should be "-f".
- Also, when -f errors outside if condition (returns non-zero value), it seems to just fail the run totally.
- Use "-f" instead of "-d"
- Move condition to if condition block
> Fix frontend env check in workflow

- .changeset/weak-oranges-exist.md
- apps/web/Dockerfile
- `web` is failing to build due to missing `.prettierrc.js` during build
> Include .prettierrc.js during web build

- apps/admin-web/next.config.js
- apps/web/Dockerfile
- apps/web/next.config.js
- Next.js lints before building by default, which cause build to fail if .prettierrc.js is not present.
- Disable linting during Next.js builds
- Reverts #542 
> disable linting during nextjs builds

- .github/workflows/release.yaml
- "GitOps update mode" determines how it should update gitops manifest files in gitops repo. Currently, main and beta uses "pr" to update the repo, while dev uses "commit". It is annoying for developers who want to deploy beta to ask infra to deploy beta every time, as beta is supposed to be used for testing anyways.
- Use update mode "commit" instead of "pr" for beta deployments
- When merging "Version Packages (beta)" PRs, it should automatically deploy to gitops.
> Use gitops-update-mode as "commit" for beta deployments

- .vscode/extensions.json
We no longer use nx
Stop recommending nx extensions
> chore: remove nx from .vscode/extensions.json

- .changeset/eighty-carrots-ring.md
- .changeset/thick-otters-accept.md
- apps/reg-scraper/src/scraper/scraper.service.ts
- packages/schema/src/mongo/course.schema.ts
- Course descriptions was missing from website, due to missing fields in mongo schema (oops)
- Add `courseDescTh` and courseDescEn` fields back
- Also introduce a temporary workaround for infinitely stuck scraper problem by exiting on rescrape if a scrape in is progress
> Fix scraper missing course description

- .changeset/big-tomatoes-sleep.md
- apps/web/src/modules/CourseSearch/index.tsx
- When changing term from top bar, term selector next to "ค้นหาวิขาเรียน" will go out of sync.
- Fix it
> Fix term selector out of sync

- .changeset/dry-trainers-knock.md
- apps/web/src/common/utils/getExamPeriod/index.ts
- apps/web/src/modules/CourseDetail/index.tsx
- apps/web/src/modules/Schedule/components/CourseDialog/components/CourseDialogDetail.tsx
- because TBA null - null, due to some graphql lib changes which always populates field midterm and final as
```
midterm: {
date: null
period: {
start: null
start: null
}
}
```
instead of 
```
midterm: null
```
- fix the conditions in dialog page and course detail page
test in dev before merge
> fix: TBA null - null

- .changeset/dry-crabs-thank.md
- apps/web/src/modules/Schedule/components/CourseDialog/components/CourseDialogDetail.tsx
- So, I was experimenting with using `gpt-3.5-turbo` to review code changes. It appears that it catches a mistake in #602.
- Fix the component to display final exam date and period in final exam slot
> Fix midterm exam date displays as final exam

- .changeset/dull-schools-doubt.md
- apps/web/src/common/components/TopBar/components/AnnouncementBar/announcements.ts
- apps/web/src/common/components/TopBar/index.tsx
- apps/web/src/common/constants/terms.ts
Enable options for 2567, however data will be unavailable until scraper problem is fixed
> feat(web): enable 2567 with warnings

- .changeset/pre.json
- .changeset/real-mails-beg.md
- .changeset/rich-grapes-kiss.md
- .changeset/shikanoko-nokonoko-koshitantan.md
- apps/web/CHANGELOG.md
- apps/web/package.json
- apps/web/src/pages/[studyProgram]/schedule/import/index.tsx
> Deploy Production 13/7/67

- packages/ui/src/components/checkbox/checkbox.stories.svelte
- packages/ui/src/components/checkbox/checkbox.svelte
- improve accessibility for checkbox components
- add `aria-label` attributes for accessibility
> style(v2): update `aria-label` for accessibility of checkbox

- packages/ui/src/components/button/index.ts
- packages/ui/src/components/table/table-cell.svelte
- packages/ui/src/components/table/table.stories.svelte
- Correcting Component style 
- fix style in primary outlined `button` and add base font of button as "FC Orbit" or "font-sans"
- update style in `table.cell` when use rowspan and and base font as "Sarabun" or "font-sarabun"
- add description in Table storybook about `table.cell` to use rowspan
> style(v2)/fix component style
